cmake: Don't backslash-escape default rawwave path
Since the switch to native cmake functions this double escape is not necessary, and
causes a build failure when building with -DDEFAULT_STK_RAWWAVE_PATH=/some/path:

<command-line>:0:23: warning: missing terminating " character
<command-line>:0:22: error: stray ‘\’ in program
../Opcodes/stk/stkOpcodes.cpp:742:16: note: in expansion of macro ‘DEFAULT_RAWWAVE_PATH’
         path = DEFAULT_RAWWAVE_PATH;
                ^~~~~~~~~~~~~~~~~~~~
<command-line>:0:23: error: missing terminating " character
../Opcodes/stk/stkOpcodes.cpp:742:16: note: in expansion of macro ‘DEFAULT_RAWWAVE_PATH’
         path = DEFAULT_RAWWAVE_PATH;
                ^~~~~~~~~~~~~~~~~~~~
../Opcodes/stk/stkOpcodes.cpp: In function ‘int csoundModuleInit(CSOUND*)’:
../Opcodes/stk/stkOpcodes.cpp:742:36: error: expected primary-expression before ‘;’ token
         path = DEFAULT_RAWWAVE_PATH;
                                    ^

Just remove it and the build is fixed