Update libogg to use github instead of gitlab for download
This should fix the intermittent errors seen in the github workflow runners:

    error: Missing xiph-ogg-v1.3.5.tar.gz and downloads are blocked by x-block-origin.
    error: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: curl failed to download with exit code 22

This pr changes the libogg port to use github instead of gitlab.