threadsafe.c: Fix unused variable warning/error
| Top/threadsafe.c:537:5: error: variable 'x' set but not used [-Werror=unused-but-set-variable]
|    } x;
|      ^
| cc1: all warnings being treated as errors

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>